### ISSUE TITLE
Ignore HTTP error 999 from LinkedIn

### ISSUE THREAD

**Issue by ricalo** [Ricalo/JekyllDocker#12]
HtmlProofer fails with an HTTP error 999 when checking LinkedIn URLs.
```
*  External link https://www.linkedin.com/in/... failed: 999 No error
```
HtmlProofer should ignore such errors.

**Comment by Ricalo** [comment]
Won't fix. Conflicts with #14

**Comment by ricalo** [comment]
Mmm... this actually can't be fixed by developers. I'll keep this open to think about a solution.

**Comment by ricalo** [comment]
For now, I'll just ignore http error 999
